export const USER_REGISTER = `USER_REGISTER`
export const USER_REGISTER_FULFILLED = `USER_REGISTER_FULFILLED`


export const GET_QUESTION = `GET_QUESTION`
export const GET_QUESTION_FULFILLED = `GET_QUESTION_FULFILLED`

export const SEND_ANSWER = `SEND_ANSWER`